version: '3.8'

services:
  graph-db-instance:
    image: khaller/graphdb-free:10.6.2
    command: ["--GDB_HEAP_SIZE", "4GB"]
    container_name: "graph-db-instance"
    ports:
      - 7515:7200
    volumes:
    - "./imaging-plaza-backups/db/data:/opt/graphdb/data:rw"
    - "./imaging-plaza-backups/db/logs:/opt/graphdb/logs:rw"
    - "./imaging-plaza-backups/db/work:/opt/graphdb/work:rw"
    networks:
      - plaza-network

  gimie-api:
    build: 
      context: gimie-api
      dockerfile: Dockerfile
    container_name: "gimie-api"
    env_file:
      - .env
    ports:
      - 8002:15400
    # volumes:
    #   - "./gimie-api/app:/app"
    # entrypoint: bash
    # stdin_open: true
    # tty: true
    networks:
      - plaza-network

  shacl-validator-api:
    build: 
      context: shacl-api
      dockerfile: Dockerfile
    container_name: "shacl-validator-api"
    ports:
      - 8000:15400
      - 8501:8501
    # volumes:
    #   - "./shacl-api/app:/app"
    # entrypoint: bash 
    # stdin_open: true
    # tty: true
    networks:
      - plaza-network

  fair-indicator-api:
    build: 
      context: imaging-plaza-fair-indicator-api
      dockerfile: Dockerfile
    container_name: "fair-indicator-api"
    ports:
      - 8001:15400
      - 8502:8501
    # volumes:
    #   - "./imaging-plaza-fair-indicator-api/imaging_plaza_fair_indicator_api:/app/imaging_plaza_fair_indicator_api"
    # entrypoint: bash
    # stdin_open: true
    # tty: true
    networks:
      - plaza-network

  frontend:
    build: 
      context: imaging-plaza-frontend-public
      dockerfile: Dockerfile
      args:
        COTERIES_TOKEN: ${COTERIES_TOKEN}
        FONTAWESOME_TOKEN: ${FONTAWESOME_TOKEN}
    entrypoint: ["bash", "cp", "/app/config/.env.local", "/app/.env.local", "&&", "npm", "install", "&&", "npm", "run", "build"]
    container_name: "frontend"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      #- "./imaging-plaza-frontend:/app"
      - "./config:/app/config"
    depends_on:
      - graph-db-instance
      - gimie-api
      - shacl-validator-api
      - fair-indicator-api
    networks:
      - plaza-network

networks:
  plaza-network:
    driver: bridge

